export type Country = {
  code: string;
  name: string;
  /** null when the country has no postal code system */
  postal: RegExp | null;
  postalExample?: string;
  /** average residential electricity tariff, USD/kWh (indicative) */
  tariff: number;
  /** indicative installed cost, USD per kW */
  costPerKw: number;
  currency: string;
  /** rough currency conversion from USD, for display only */
  fx: number;
  lang?: string;
};

// Postal patterns are deliberately permissive format checks (layer 1 only).
export const COUNTRIES: Country[] = [
  { code: "IN", name: "India", postal: /^[1-9]\d{5}$/, postalExample: "560001", tariff: 0.09, costPerKw: 620, currency: "INR", fx: 96, lang: "hi" },
  { code: "US", name: "United States", postal: /^\d{5}(-\d{4})?$/, postalExample: "94303", tariff: 0.17, costPerKw: 2600, currency: "USD", fx: 1, lang: "en" },
  { code: "GB", name: "United Kingdom", postal: /^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i, postalExample: "SW1A 1AA", tariff: 0.3, costPerKw: 1900, currency: "GBP", fx: 0.78, lang: "en" },
  { code: "DE", name: "Germany", postal: /^\d{5}$/, postalExample: "10115", tariff: 0.36, costPerKw: 1500, currency: "EUR", fx: 0.92, lang: "de" },
  { code: "FR", name: "France", postal: /^\d{5}$/, postalExample: "75001", tariff: 0.25, costPerKw: 2000, currency: "EUR", fx: 0.92, lang: "fr" },
  { code: "ES", name: "Spain", postal: /^\d{5}$/, postalExample: "28001", tariff: 0.24, costPerKw: 1400, currency: "EUR", fx: 0.92, lang: "es" },
  { code: "IT", name: "Italy", postal: /^\d{5}$/, postalExample: "00100", tariff: 0.31, costPerKw: 1700, currency: "EUR", fx: 0.92 },
  { code: "PT", name: "Portugal", postal: /^\d{4}-\d{3}$/, postalExample: "1000-001", tariff: 0.24, costPerKw: 1400, currency: "EUR", fx: 0.92, lang: "pt" },
  { code: "NL", name: "Netherlands", postal: /^\d{4}\s?[A-Z]{2}$/i, postalExample: "1011 AB", tariff: 0.32, costPerKw: 1500, currency: "EUR", fx: 0.92 },
  { code: "BE", name: "Belgium", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.34, costPerKw: 1600, currency: "EUR", fx: 0.92 },
  { code: "CH", name: "Switzerland", postal: /^\d{4}$/, postalExample: "8001", tariff: 0.3, costPerKw: 2200, currency: "CHF", fx: 0.88 },
  { code: "AT", name: "Austria", postal: /^\d{4}$/, postalExample: "1010", tariff: 0.28, costPerKw: 1600, currency: "EUR", fx: 0.92, lang: "de" },
  { code: "SE", name: "Sweden", postal: /^\d{3}\s?\d{2}$/, postalExample: "111 20", tariff: 0.2, costPerKw: 1600, currency: "SEK", fx: 10.5 },
  { code: "NO", name: "Norway", postal: /^\d{4}$/, postalExample: "0150", tariff: 0.15, costPerKw: 1800, currency: "NOK", fx: 10.8 },
  { code: "DK", name: "Denmark", postal: /^\d{4}$/, postalExample: "1050", tariff: 0.35, costPerKw: 1600, currency: "DKK", fx: 6.9 },
  { code: "FI", name: "Finland", postal: /^\d{5}$/, postalExample: "00100", tariff: 0.2, costPerKw: 1600, currency: "EUR", fx: 0.92 },
  { code: "PL", name: "Poland", postal: /^\d{2}-\d{3}$/, postalExample: "00-001", tariff: 0.2, costPerKw: 1200, currency: "PLN", fx: 4 },
  { code: "TR", name: "Türkiye", postal: /^\d{5}$/, postalExample: "34000", tariff: 0.1, costPerKw: 900, currency: "TRY", fx: 41, lang: "tr" },
  { code: "RU", name: "Russia", postal: /^\d{6}$/, postalExample: "101000", tariff: 0.06, costPerKw: 1000, currency: "RUB", fx: 90, lang: "ru" },
  { code: "UA", name: "Ukraine", postal: /^\d{5}$/, postalExample: "01001", tariff: 0.07, costPerKw: 1000, currency: "UAH", fx: 41 },
  { code: "BR", name: "Brazil", postal: /^\d{5}-?\d{3}$/, postalExample: "01001-000", tariff: 0.16, costPerKw: 800, currency: "BRL", fx: 5.4, lang: "pt" },
  { code: "MX", name: "Mexico", postal: /^\d{5}$/, postalExample: "01000", tariff: 0.11, costPerKw: 1000, currency: "MXN", fx: 18, lang: "es" },
  { code: "AR", name: "Argentina", postal: /^[A-Z]?\d{4}[A-Z]{0,3}$/i, postalExample: "C1000", tariff: 0.07, costPerKw: 1100, currency: "ARS", fx: 1000, lang: "es" },
  { code: "CL", name: "Chile", postal: /^\d{7}$/, postalExample: "8320000", tariff: 0.17, costPerKw: 1100, currency: "CLP", fx: 960, lang: "es" },
  { code: "CO", name: "Colombia", postal: /^\d{6}$/, postalExample: "110111", tariff: 0.16, costPerKw: 1100, currency: "COP", fx: 4100, lang: "es" },
  { code: "CA", name: "Canada", postal: /^[A-Z]\d[A-Z]\s?\d[A-Z]\d$/i, postalExample: "K1A 0B1", tariff: 0.13, costPerKw: 2200, currency: "CAD", fx: 1.38 },
  { code: "AU", name: "Australia", postal: /^\d{4}$/, postalExample: "2000", tariff: 0.22, costPerKw: 900, currency: "AUD", fx: 1.5 },
  { code: "NZ", name: "New Zealand", postal: /^\d{4}$/, postalExample: "6011", tariff: 0.2, costPerKw: 1600, currency: "NZD", fx: 1.65 },
  { code: "JP", name: "Japan", postal: /^\d{3}-?\d{4}$/, postalExample: "100-0001", tariff: 0.22, costPerKw: 2000, currency: "JPY", fx: 150, lang: "ja" },
  { code: "CN", name: "China", postal: /^\d{6}$/, postalExample: "100000", tariff: 0.08, costPerKw: 700, currency: "CNY", fx: 7.2, lang: "zh" },
  { code: "KR", name: "South Korea", postal: /^\d{5}$/, postalExample: "04524", tariff: 0.1, costPerKw: 1300, currency: "KRW", fx: 1350 },
  { code: "TW", name: "Taiwan", postal: /^\d{3}(\d{2})?$/, postalExample: "100", tariff: 0.09, costPerKw: 1200, currency: "TWD", fx: 32 },
  { code: "ID", name: "Indonesia", postal: /^\d{5}$/, postalExample: "10110", tariff: 0.1, costPerKw: 800, currency: "IDR", fx: 16000, lang: "id" },
  { code: "MY", name: "Malaysia", postal: /^\d{5}$/, postalExample: "50000", tariff: 0.12, costPerKw: 800, currency: "MYR", fx: 4.4 },
  { code: "SG", name: "Singapore", postal: /^\d{6}$/, postalExample: "018956", tariff: 0.23, costPerKw: 1200, currency: "SGD", fx: 1.34 },
  { code: "TH", name: "Thailand", postal: /^\d{5}$/, postalExample: "10200", tariff: 0.13, costPerKw: 850, currency: "THB", fx: 34 },
  { code: "VN", name: "Vietnam", postal: /^\d{6}$/, postalExample: "100000", tariff: 0.08, costPerKw: 700, currency: "VND", fx: 25000, lang: "vi" },
  { code: "PH", name: "Philippines", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.19, costPerKw: 950, currency: "PHP", fx: 58 },
  { code: "BD", name: "Bangladesh", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.07, costPerKw: 700, currency: "BDT", fx: 120, lang: "bn" },
  { code: "PK", name: "Pakistan", postal: /^\d{5}$/, postalExample: "44000", tariff: 0.09, costPerKw: 600, currency: "PKR", fx: 280, lang: "ur" },
  { code: "LK", name: "Sri Lanka", postal: /^\d{5}$/, postalExample: "00100", tariff: 0.08, costPerKw: 700, currency: "LKR", fx: 300 },
  { code: "NP", name: "Nepal", postal: /^\d{5}$/, postalExample: "44600", tariff: 0.07, costPerKw: 750, currency: "NPR", fx: 140, lang: "hi" },
  { code: "AE", name: "United Arab Emirates", postal: null, tariff: 0.08, costPerKw: 800, currency: "AED", fx: 3.67, lang: "ar" },
  { code: "SA", name: "Saudi Arabia", postal: /^\d{5}(-\d{4})?$/, postalExample: "11564", tariff: 0.05, costPerKw: 750, currency: "SAR", fx: 3.75, lang: "ar" },
  { code: "QA", name: "Qatar", postal: null, tariff: 0.03, costPerKw: 800, currency: "QAR", fx: 3.64, lang: "ar" },
  { code: "KW", name: "Kuwait", postal: /^\d{5}$/, postalExample: "13001", tariff: 0.03, costPerKw: 800, currency: "KWD", fx: 0.31, lang: "ar" },
  { code: "OM", name: "Oman", postal: /^\d{3}$/, postalExample: "100", tariff: 0.05, costPerKw: 800, currency: "OMR", fx: 0.38, lang: "ar" },
  { code: "EG", name: "Egypt", postal: /^\d{5}$/, postalExample: "11511", tariff: 0.04, costPerKw: 700, currency: "EGP", fx: 48, lang: "ar" },
  { code: "MA", name: "Morocco", postal: /^\d{5}$/, postalExample: "10000", tariff: 0.12, costPerKw: 900, currency: "MAD", fx: 10, lang: "ar" },
  { code: "ZA", name: "South Africa", postal: /^\d{4}$/, postalExample: "0001", tariff: 0.15, costPerKw: 900, currency: "ZAR", fx: 18 },
  { code: "KE", name: "Kenya", postal: /^\d{5}$/, postalExample: "00100", tariff: 0.16, costPerKw: 1000, currency: "KES", fx: 130, lang: "sw" },
  { code: "TZ", name: "Tanzania", postal: /^\d{5}$/, postalExample: "11101", tariff: 0.1, costPerKw: 1000, currency: "TZS", fx: 2700, lang: "sw" },
  { code: "UG", name: "Uganda", postal: null, tariff: 0.19, costPerKw: 1100, currency: "UGX", fx: 3700, lang: "sw" },
  { code: "NG", name: "Nigeria", postal: /^\d{6}$/, postalExample: "100001", tariff: 0.06, costPerKw: 1000, currency: "NGN", fx: 1550 },
  { code: "GH", name: "Ghana", postal: /^[A-Z]{2}-?\d{3,4}-?\d{4}$/i, postalExample: "GA-005-0001", tariff: 0.09, costPerKw: 1000, currency: "GHS", fx: 15 },
  { code: "ET", name: "Ethiopia", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.03, costPerKw: 1100, currency: "ETB", fx: 120 },
  { code: "IE", name: "Ireland", postal: /^[A-Z]\d{2}\s?[A-Z\d]{4}$/i, postalExample: "D02 AF30", tariff: 0.35, costPerKw: 1900, currency: "EUR", fx: 0.92 },
  { code: "GR", name: "Greece", postal: /^\d{3}\s?\d{2}$/, postalExample: "104 31", tariff: 0.24, costPerKw: 1300, currency: "EUR", fx: 0.92 },
  { code: "IL", name: "Israel", postal: /^\d{5}(\d{2})?$/, postalExample: "9103401", tariff: 0.15, costPerKw: 1100, currency: "ILS", fx: 3.7 },
  { code: "HK", name: "Hong Kong", postal: null, tariff: 0.16, costPerKw: 1500, currency: "HKD", fx: 7.8, lang: "zh" },
  { code: "AO", name: "Angola", postal: null, tariff: 0.04, costPerKw: 1200, currency: "AOA", fx: 900, lang: "pt" },
  { code: "PA", name: "Panama", postal: null, tariff: 0.17, costPerKw: 1100, currency: "USD", fx: 1, lang: "es" },
  { code: "FJ", name: "Fiji", postal: null, tariff: 0.17, costPerKw: 1400, currency: "FJD", fx: 2.25 },
  { code: "CZ", name: "Czechia", postal: /^\d{3}\s?\d{2}$/, postalExample: "110 00", tariff: 0.28, costPerKw: 1300, currency: "CZK", fx: 23 },
  { code: "SK", name: "Slovakia", postal: /^\d{3}\s?\d{2}$/, postalExample: "811 01", tariff: 0.22, costPerKw: 1300, currency: "EUR", fx: 0.92 },
  { code: "HU", name: "Hungary", postal: /^\d{4}$/, postalExample: "1011", tariff: 0.11, costPerKw: 1200, currency: "HUF", fx: 360 },
  { code: "RO", name: "Romania", postal: /^\d{6}$/, postalExample: "010011", tariff: 0.18, costPerKw: 1100, currency: "RON", fx: 4.6 },
  { code: "BG", name: "Bulgaria", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.13, costPerKw: 1000, currency: "BGN", fx: 1.8 },
  { code: "HR", name: "Croatia", postal: /^\d{5}$/, postalExample: "10000", tariff: 0.16, costPerKw: 1200, currency: "EUR", fx: 0.92 },
  { code: "SI", name: "Slovenia", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.18, costPerKw: 1300, currency: "EUR", fx: 0.92 },
  { code: "RS", name: "Serbia", postal: /^\d{5}$/, postalExample: "11000", tariff: 0.09, costPerKw: 1000, currency: "RSD", fx: 108 },
  { code: "LT", name: "Lithuania", postal: /^(LT-)?\d{5}$/i, postalExample: "01100", tariff: 0.22, costPerKw: 1200, currency: "EUR", fx: 0.92 },
  { code: "LV", name: "Latvia", postal: /^(LV-)?\d{4}$/i, postalExample: "LV-1050", tariff: 0.22, costPerKw: 1200, currency: "EUR", fx: 0.92 },
  { code: "EE", name: "Estonia", postal: /^\d{5}$/, postalExample: "10111", tariff: 0.21, costPerKw: 1200, currency: "EUR", fx: 0.92 },
  { code: "IS", name: "Iceland", postal: /^\d{3}$/, postalExample: "101", tariff: 0.12, costPerKw: 2200, currency: "ISK", fx: 138 },
  { code: "LU", name: "Luxembourg", postal: /^(L-)?\d{4}$/i, postalExample: "1111", tariff: 0.25, costPerKw: 1700, currency: "EUR", fx: 0.92 },
  { code: "CY", name: "Cyprus", postal: /^\d{4}$/, postalExample: "1010", tariff: 0.28, costPerKw: 1100, currency: "EUR", fx: 0.92 },
  { code: "MT", name: "Malta", postal: /^[A-Z]{3}\s?\d{4}$/i, postalExample: "VLT 1111", tariff: 0.14, costPerKw: 1400, currency: "EUR", fx: 0.92 },
  { code: "AL", name: "Albania", postal: /^\d{4}$/, postalExample: "1001", tariff: 0.1, costPerKw: 1000, currency: "ALL", fx: 90 },
  { code: "GE", name: "Georgia", postal: /^\d{4}$/, postalExample: "0105", tariff: 0.07, costPerKw: 950, currency: "GEL", fx: 2.7 },
  { code: "AM", name: "Armenia", postal: /^\d{4}$/, postalExample: "0010", tariff: 0.11, costPerKw: 950, currency: "AMD", fx: 385 },
  { code: "AZ", name: "Azerbaijan", postal: /^(AZ)?\s?\d{4}$/i, postalExample: "AZ1000", tariff: 0.049, costPerKw: 1000, currency: "AZN", fx: 1.7 },
  { code: "KZ", name: "Kazakhstan", postal: /^\d{6}$/, postalExample: "010000", tariff: 0.05, costPerKw: 900, currency: "KZT", fx: 520, lang: "ru" },
  { code: "UZ", name: "Uzbekistan", postal: /^\d{6}$/, postalExample: "100000", tariff: 0.03, costPerKw: 850, currency: "UZS", fx: 12600, lang: "ru" },
  { code: "IQ", name: "Iraq", postal: /^\d{5}$/, postalExample: "10001", tariff: 0.03, costPerKw: 900, currency: "IQD", fx: 1310, lang: "ar" },
  { code: "JO", name: "Jordan", postal: /^\d{5}$/, postalExample: "11118", tariff: 0.12, costPerKw: 800, currency: "JOD", fx: 0.71, lang: "ar" },
  { code: "LB", name: "Lebanon", postal: /^\d{4}\s?\d{4}$/, postalExample: "1107 2020", tariff: 0.1, costPerKw: 900, currency: "USD", fx: 1, lang: "ar" },
  { code: "BH", name: "Bahrain", postal: /^\d{3,4}$/, postalExample: "317", tariff: 0.08, costPerKw: 800, currency: "BHD", fx: 0.38, lang: "ar" },
  { code: "TN", name: "Tunisia", postal: /^\d{4}$/, postalExample: "1000", tariff: 0.08, costPerKw: 900, currency: "TND", fx: 3.1, lang: "ar" },
  { code: "DZ", name: "Algeria", postal: /^\d{5}$/, postalExample: "16000", tariff: 0.04, costPerKw: 900, currency: "DZD", fx: 134, lang: "ar" },
  { code: "LY", name: "Libya", postal: null, tariff: 0.02, costPerKw: 1000, currency: "LYD", fx: 4.8, lang: "ar" },
  { code: "SN", name: "Senegal", postal: /^\d{5}$/, postalExample: "10200", tariff: 0.2, costPerKw: 1100, currency: "XOF", fx: 605, lang: "fr" },
  { code: "CI", name: "Côte d'Ivoire", postal: null, tariff: 0.14, costPerKw: 1100, currency: "XOF", fx: 605, lang: "fr" },
  { code: "CM", name: "Cameroon", postal: null, tariff: 0.13, costPerKw: 1100, currency: "XAF", fx: 605, lang: "fr" },
  { code: "RW", name: "Rwanda", postal: null, tariff: 0.19, costPerKw: 1100, currency: "RWF", fx: 1350, lang: "fr" },
  { code: "ZM", name: "Zambia", postal: /^\d{5}$/, postalExample: "10101", tariff: 0.05, costPerKw: 1100, currency: "ZMW", fx: 26 },
  { code: "MZ", name: "Mozambique", postal: /^\d{4}$/, postalExample: "1100", tariff: 0.08, costPerKw: 1100, currency: "MZN", fx: 64, lang: "pt" },
  { code: "BW", name: "Botswana", postal: null, tariff: 0.11, costPerKw: 1100, currency: "BWP", fx: 13.5 },
  { code: "NA", name: "Namibia", postal: null, tariff: 0.12, costPerKw: 1100, currency: "NAD", fx: 18 },
  { code: "MU", name: "Mauritius", postal: /^\d{5}$/, postalExample: "11324", tariff: 0.14, costPerKw: 1200, currency: "MUR", fx: 46 },
  { code: "MG", name: "Madagascar", postal: /^\d{3}$/, postalExample: "101", tariff: 0.11, costPerKw: 1200, currency: "MGA", fx: 4500, lang: "fr" },
  { code: "PE", name: "Peru", postal: /^\d{5}$/, postalExample: "15001", tariff: 0.18, costPerKw: 1100, currency: "PEN", fx: 3.7, lang: "es" },
  { code: "EC", name: "Ecuador", postal: /^\d{6}$/, postalExample: "170101", tariff: 0.1, costPerKw: 1100, currency: "USD", fx: 1, lang: "es" },
  { code: "BO", name: "Bolivia", postal: null, tariff: 0.09, costPerKw: 1100, currency: "BOB", fx: 6.9, lang: "es" },
  { code: "UY", name: "Uruguay", postal: /^\d{5}$/, postalExample: "11000", tariff: 0.23, costPerKw: 1300, currency: "UYU", fx: 40, lang: "es" },
  { code: "PY", name: "Paraguay", postal: /^\d{4}$/, postalExample: "1101", tariff: 0.06, costPerKw: 1100, currency: "PYG", fx: 7500, lang: "es" },
  { code: "CR", name: "Costa Rica", postal: /^\d{5}$/, postalExample: "10101", tariff: 0.17, costPerKw: 1300, currency: "CRC", fx: 510, lang: "es" },
  { code: "GT", name: "Guatemala", postal: /^\d{5}$/, postalExample: "01001", tariff: 0.21, costPerKw: 1200, currency: "GTQ", fx: 7.7, lang: "es" },
  { code: "DO", name: "Dominican Republic", postal: /^\d{5}$/, postalExample: "10101", tariff: 0.16, costPerKw: 1200, currency: "DOP", fx: 60, lang: "es" },
  { code: "JM", name: "Jamaica", postal: null, tariff: 0.28, costPerKw: 1500, currency: "JMD", fx: 157 },
  { code: "TT", name: "Trinidad & Tobago", postal: /^\d{6}$/, postalExample: "120110", tariff: 0.05, costPerKw: 1400, currency: "TTD", fx: 6.8 },
  { code: "MM", name: "Myanmar", postal: /^\d{5}$/, postalExample: "11181", tariff: 0.04, costPerKw: 800, currency: "MMK", fx: 2100 },
  { code: "KH", name: "Cambodia", postal: /^\d{5,6}$/, postalExample: "120101", tariff: 0.18, costPerKw: 850, currency: "KHR", fx: 4050 },
  { code: "LA", name: "Laos", postal: /^\d{5}$/, postalExample: "01000", tariff: 0.07, costPerKw: 900, currency: "LAK", fx: 21500 },
  { code: "MN", name: "Mongolia", postal: /^\d{5}$/, postalExample: "14200", tariff: 0.06, costPerKw: 1000, currency: "MNT", fx: 3450 },
  { code: "BT", name: "Bhutan", postal: /^\d{5}$/, postalExample: "11001", tariff: 0.03, costPerKw: 800, currency: "BTN", fx: 96 },
  { code: "MV", name: "Maldives", postal: /^\d{5}$/, postalExample: "20026", tariff: 0.25, costPerKw: 1300, currency: "MVR", fx: 15.4 },
  { code: "PG", name: "Papua New Guinea", postal: /^\d{3}$/, postalExample: "111", tariff: 0.22, costPerKw: 1600, currency: "PGK", fx: 4 },
  { code: "PR", name: "Puerto Rico", postal: /^\d{5}(-\d{4})?$/, postalExample: "00901", tariff: 0.27, costPerKw: 2400, currency: "USD", fx: 1, lang: "es" },
  { code: "ZW", name: "Zimbabwe", postal: null, tariff: 0.1, costPerKw: 1100, currency: "USD", fx: 1 },
];

export const DEFAULT_COUNTRY: Country = {
  code: "US",
  name: "United States",
  postal: /^\d{5}(-\d{4})?$/,
  tariff: 0.15,
  costPerKw: 2000,
  currency: "USD",
  fx: 1,
};

export function getCountry(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code);
}
